import type {
  User, Organization, Vulnerability, Asset, Incident,
  ThreatIntel, ComplianceFramework, PenTestProject, TrainingCourse,
  Notification, DashboardStats, ChartDataPoint
} from "@/types";

export const MOCK_USER: User = {
  id: "usr_001",
  email: "alex.morgan@getcyber.io",
  name: "Alex Morgan",
  role: "security_analyst",
  organizationId: "org_001",
  organizationName: "TechCorp Industries",
  mfaEnabled: true,
  lastLogin: "2026-07-09T08:30:00Z",
  createdAt: "2025-01-15T10:00:00Z",
  plan: "enterprise",
  permissions: ["view_all", "manage_vulnerabilities", "manage_incidents", "generate_reports", "manage_assets"],
};

export const MOCK_ORGANIZATION: Organization = {
  id: "org_001",
  name: "TechCorp Industries",
  domain: "techcorp.com",
  industry: "Technology",
  size: "500-1000",
  plan: "enterprise",
  membersCount: 47,
  assetsCount: 312,
  riskScore: 68,
  complianceScore: 82,
  createdAt: "2024-03-01T00:00:00Z",
  status: "active",
};

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  riskScore: 68,
  riskTrend: -5,
  totalAssets: 312,
  activeThreats: 23,
  openVulnerabilities: 147,
  criticalVulnerabilities: 12,
  openIncidents: 8,
  complianceScore: 82,
  securityScore: 74,
  patchCompliance: 71,
  activeScans: 3,
  trainingCompletion: 64,
};

export const MOCK_VULNERABILITIES: Vulnerability[] = [
  {
    id: "vuln_001",
    title: "SQL Injection in User Authentication Module",
    description: "The login form is vulnerable to SQL injection attacks allowing unauthorized database access.",
    severity: "critical",
    cvssScore: 9.8,
    cve: "CVE-2024-1234",
    asset: "webapp-portal.techcorp.com",
    assetType: "webapp",
    status: "open",
    discoveredAt: "2026-07-08T14:23:00Z",
    updatedAt: "2026-07-09T09:00:00Z",
    assignedTo: "Alex Morgan",
    recommendation: "Implement parameterized queries and input validation immediately.",
    category: "Injection",
    exploitable: true,
  },
  {
    id: "vuln_002",
    title: "Remote Code Execution via Deserialization",
    description: "Unsafe deserialization of user-supplied data enables remote code execution.",
    severity: "critical",
    cvssScore: 9.6,
    cve: "CVE-2024-5678",
    asset: "api.techcorp.com",
    assetType: "api",
    status: "in_progress",
    discoveredAt: "2026-07-07T10:00:00Z",
    updatedAt: "2026-07-09T08:00:00Z",
    assignedTo: "Sarah Chen",
    recommendation: "Upgrade serialization libraries and implement whitelist validation.",
    category: "Deserialization",
    exploitable: true,
  },
  {
    id: "vuln_003",
    title: "Cross-Site Scripting (XSS) in Dashboard",
    description: "Stored XSS vulnerability in user profile fields allows script injection.",
    severity: "high",
    cvssScore: 8.1,
    cve: "CVE-2024-9012",
    asset: "dashboard.techcorp.com",
    assetType: "webapp",
    status: "open",
    discoveredAt: "2026-07-06T16:00:00Z",
    updatedAt: "2026-07-08T11:00:00Z",
    assignedTo: "Mike Johnson",
    recommendation: "Implement output encoding and Content Security Policy headers.",
    category: "XSS",
    exploitable: true,
  },
  {
    id: "vuln_004",
    title: "Outdated OpenSSL Library",
    description: "Server running OpenSSL 1.0.2 with multiple known vulnerabilities.",
    severity: "high",
    cvssScore: 7.5,
    cve: "CVE-2024-3456",
    asset: "prod-server-01.techcorp.com",
    assetType: "server",
    status: "in_progress",
    discoveredAt: "2026-07-05T09:00:00Z",
    updatedAt: "2026-07-07T14:00:00Z",
    assignedTo: "Alex Morgan",
    recommendation: "Update OpenSSL to version 3.x immediately.",
    category: "Outdated Software",
    exploitable: false,
  },
  {
    id: "vuln_005",
    title: "Weak SSL/TLS Configuration",
    description: "Server supports deprecated TLS 1.0 and weak cipher suites.",
    severity: "medium",
    cvssScore: 5.9,
    asset: "mail.techcorp.com",
    assetType: "server",
    status: "open",
    discoveredAt: "2026-07-04T12:00:00Z",
    updatedAt: "2026-07-06T09:00:00Z",
    recommendation: "Disable TLS 1.0/1.1 and configure strong cipher suites.",
    category: "Cryptography",
    exploitable: false,
  },
  {
    id: "vuln_006",
    title: "Missing HTTP Security Headers",
    description: "Application missing critical security headers including X-Frame-Options and HSTS.",
    severity: "medium",
    cvssScore: 5.3,
    asset: "webapp-portal.techcorp.com",
    assetType: "webapp",
    status: "resolved",
    discoveredAt: "2026-07-03T08:00:00Z",
    updatedAt: "2026-07-05T16:00:00Z",
    recommendation: "Implement security headers via web server configuration.",
    category: "Security Misconfiguration",
    exploitable: false,
  },
  {
    id: "vuln_007",
    title: "Default Credentials on Network Switch",
    description: "Network switch accessible with default admin credentials.",
    severity: "critical",
    cvssScore: 9.3,
    asset: "switch-core-01",
    assetType: "network",
    status: "open",
    discoveredAt: "2026-07-09T07:00:00Z",
    updatedAt: "2026-07-09T07:00:00Z",
    recommendation: "Change default credentials immediately and implement ACL.",
    category: "Authentication",
    exploitable: true,
  },
  {
    id: "vuln_008",
    title: "Insecure Direct Object Reference",
    description: "API endpoints expose internal object references allowing unauthorized data access.",
    severity: "high",
    cvssScore: 7.8,
    asset: "api.techcorp.com",
    assetType: "api",
    status: "open",
    discoveredAt: "2026-07-08T11:00:00Z",
    updatedAt: "2026-07-08T11:00:00Z",
    recommendation: "Implement proper authorization checks on all API endpoints.",
    category: "Broken Access Control",
    exploitable: true,
  },
];

export const MOCK_ASSETS: Asset[] = [
  {
    id: "ast_001",
    name: "webapp-portal.techcorp.com",
    type: "webapp",
    url: "https://webapp-portal.techcorp.com",
    status: "online",
    riskScore: 85,
    vulnerabilities: 12,
    lastScanned: "2026-07-09T08:00:00Z",
    owner: "Alex Morgan",
    environment: "production",
    patchStatus: "needs_update",
    tags: ["critical", "customer-facing", "portal"],
  },
  {
    id: "ast_002",
    name: "prod-server-01",
    type: "server",
    ip: "10.0.1.10",
    os: "Ubuntu 22.04 LTS",
    status: "online",
    riskScore: 62,
    vulnerabilities: 8,
    lastScanned: "2026-07-09T06:00:00Z",
    owner: "IT Team",
    environment: "production",
    patchStatus: "needs_update",
    tags: ["production", "database", "linux"],
  },
  {
    id: "ast_003",
    name: "api.techcorp.com",
    type: "api",
    url: "https://api.techcorp.com",
    status: "online",
    riskScore: 77,
    vulnerabilities: 15,
    lastScanned: "2026-07-08T20:00:00Z",
    owner: "Dev Team",
    environment: "production",
    patchStatus: "critical",
    tags: ["api", "public", "critical"],
  },
  {
    id: "ast_004",
    name: "mail.techcorp.com",
    type: "server",
    ip: "10.0.1.20",
    os: "CentOS 8",
    status: "online",
    riskScore: 45,
    vulnerabilities: 5,
    lastScanned: "2026-07-07T12:00:00Z",
    owner: "IT Team",
    environment: "production",
    patchStatus: "up_to_date",
    tags: ["email", "internal", "linux"],
  },
  {
    id: "ast_005",
    name: "vpn.techcorp.com",
    type: "network",
    ip: "10.0.0.1",
    status: "online",
    riskScore: 38,
    vulnerabilities: 3,
    lastScanned: "2026-07-06T08:00:00Z",
    owner: "Network Team",
    environment: "production",
    patchStatus: "up_to_date",
    tags: ["vpn", "network", "security"],
  },
  {
    id: "ast_006",
    name: "aws-prod-cluster",
    type: "cloud",
    status: "online",
    riskScore: 55,
    vulnerabilities: 7,
    lastScanned: "2026-07-09T04:00:00Z",
    owner: "Cloud Team",
    environment: "production",
    patchStatus: "needs_update",
    tags: ["aws", "cloud", "kubernetes"],
  },
  {
    id: "ast_007",
    name: "staging-server-01",
    type: "server",
    ip: "10.0.2.10",
    os: "Ubuntu 22.04 LTS",
    status: "online",
    riskScore: 40,
    vulnerabilities: 6,
    lastScanned: "2026-07-08T14:00:00Z",
    owner: "Dev Team",
    environment: "staging",
    patchStatus: "up_to_date",
    tags: ["staging", "testing"],
  },
  {
    id: "ast_008",
    name: "techcorp.com",
    type: "domain",
    url: "https://techcorp.com",
    status: "online",
    riskScore: 30,
    vulnerabilities: 2,
    lastScanned: "2026-07-09T07:00:00Z",
    owner: "IT Team",
    environment: "production",
    patchStatus: "up_to_date",
    tags: ["domain", "public", "primary"],
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "inc_001",
    title: "Ransomware Detection on Workstation WS-042",
    description: "Suspicious encryption activity detected on employee workstation. Possible ransomware infection.",
    severity: "critical",
    status: "in_progress",
    type: "Ransomware",
    affectedAssets: ["WS-042", "File Server"],
    assignedTo: "Alex Morgan",
    createdAt: "2026-07-09T07:30:00Z",
    updatedAt: "2026-07-09T09:15:00Z",
    priority: "p1",
    tags: ["ransomware", "encryption", "urgent"],
    timeline: [
      { id: "evt_001", timestamp: "2026-07-09T07:30:00Z", action: "Incident Created", user: "SIEM System", details: "Automated detection triggered by EDR alert" },
      { id: "evt_002", timestamp: "2026-07-09T07:45:00Z", action: "Assigned", user: "Sarah Chen", details: "Incident assigned to Alex Morgan" },
      { id: "evt_003", timestamp: "2026-07-09T08:00:00Z", action: "Isolation", user: "Alex Morgan", details: "Workstation isolated from network" },
      { id: "evt_004", timestamp: "2026-07-09T09:15:00Z", action: "Investigation", user: "Alex Morgan", details: "Analyzing malware sample in sandbox" },
    ],
  },
  {
    id: "inc_002",
    title: "Brute Force Attack on VPN Gateway",
    description: "Multiple failed login attempts detected on VPN gateway from multiple IP addresses.",
    severity: "high",
    status: "open",
    type: "Brute Force",
    affectedAssets: ["vpn.techcorp.com"],
    assignedTo: "Mike Johnson",
    createdAt: "2026-07-09T06:00:00Z",
    updatedAt: "2026-07-09T06:30:00Z",
    priority: "p2",
    tags: ["brute-force", "vpn", "authentication"],
    timeline: [
      { id: "evt_005", timestamp: "2026-07-09T06:00:00Z", action: "Detected", user: "IDS System", details: "5000+ failed login attempts in 10 minutes" },
      { id: "evt_006", timestamp: "2026-07-09T06:30:00Z", action: "Block", user: "Mike Johnson", details: "IP range blocked at firewall" },
    ],
  },
  {
    id: "inc_003",
    title: "Phishing Campaign Targeting Finance Team",
    description: "Sophisticated phishing emails targeting finance department with fake invoice attachments.",
    severity: "high",
    status: "in_progress",
    type: "Phishing",
    affectedAssets: ["Email System", "Finance Workstations"],
    assignedTo: "Sarah Chen",
    createdAt: "2026-07-08T14:00:00Z",
    updatedAt: "2026-07-09T08:00:00Z",
    priority: "p2",
    tags: ["phishing", "email", "social-engineering"],
    timeline: [
      { id: "evt_007", timestamp: "2026-07-08T14:00:00Z", action: "Reported", user: "Finance Team", details: "3 users reported suspicious emails" },
      { id: "evt_008", timestamp: "2026-07-08T15:00:00Z", action: "Analysis", user: "Sarah Chen", details: "Emails quarantined and analyzed" },
    ],
  },
  {
    id: "inc_004",
    title: "Unauthorized Data Access Detected",
    description: "Unusual access pattern detected — user accessing large volumes of customer data outside business hours.",
    severity: "critical",
    status: "open",
    type: "Insider Threat",
    affectedAssets: ["CRM Database", "Customer Portal"],
    assignedTo: "Alex Morgan",
    createdAt: "2026-07-09T03:00:00Z",
    updatedAt: "2026-07-09T03:30:00Z",
    priority: "p1",
    tags: ["insider-threat", "data-exfiltration", "unauthorized-access"],
    timeline: [
      { id: "evt_009", timestamp: "2026-07-09T03:00:00Z", action: "Alert", user: "DLP System", details: "Large data export detected at 3 AM" },
    ],
  },
];

export const MOCK_THREAT_INTEL: ThreatIntel[] = [
  {
    id: "threat_001",
    title: "LockBit 3.0 Ransomware Campaign Targeting Tech Sector",
    type: "ransomware",
    severity: "critical",
    source: "CISA Advisory",
    confidence: 95,
    ioc: ["192.168.100.50", "malware.exe", "c2-lockbit.onion"],
    description: "LockBit 3.0 operators are actively targeting technology companies with sophisticated phishing campaigns.",
    publishedAt: "2026-07-09T00:00:00Z",
    relevance: "high",
    tags: ["ransomware", "lockbit", "tech-sector", "apt"],
    ttps: ["T1566.001", "T1486", "T1490"],
  },
  {
    id: "threat_002",
    title: "APT29 Spear-Phishing Campaign Against Cloud Infrastructure",
    type: "apt",
    severity: "critical",
    source: "MITRE ATT&CK",
    confidence: 88,
    ioc: ["apt29-phishing.com", "update-microsoft-365.net"],
    description: "APT29 (Cozy Bear) conducting targeted spear-phishing campaigns against organizations using Microsoft 365.",
    publishedAt: "2026-07-08T12:00:00Z",
    relevance: "high",
    tags: ["apt29", "spear-phishing", "cloud", "microsoft"],
    ttps: ["T1566.002", "T1078", "T1550.001"],
  },
  {
    id: "threat_003",
    title: "Critical Vulnerability in Apache Log4j (Log4Shell) Variant",
    type: "vulnerability",
    severity: "critical",
    source: "NVD",
    confidence: 100,
    description: "New variant of Log4Shell vulnerability discovered affecting Log4j versions 2.x.",
    publishedAt: "2026-07-07T09:00:00Z",
    relevance: "high",
    tags: ["log4j", "rce", "critical", "java"],
    ttps: ["T1190"],
  },
  {
    id: "threat_004",
    title: "Banking Trojan AgentTesla Evolves with New Evasion Techniques",
    type: "malware",
    severity: "high",
    source: "VirusTotal Intelligence",
    confidence: 82,
    ioc: ["agent-tesla-c2.ru", "invoices-2026.zip"],
    description: "AgentTesla banking trojan updated with advanced anti-analysis and evasion capabilities.",
    publishedAt: "2026-07-06T15:00:00Z",
    relevance: "medium",
    tags: ["malware", "banking-trojan", "evasion", "stealer"],
    ttps: ["T1566.001", "T1055", "T1087"],
  },
  {
    id: "threat_005",
    title: "Massive Phishing Campaign Using Fake DocuSign Notifications",
    type: "phishing",
    severity: "high",
    source: "FBI IC3",
    confidence: 90,
    ioc: ["docusign-verify.com", "esign-document.net"],
    description: "Large-scale phishing campaign using fake DocuSign notifications to steal credentials.",
    publishedAt: "2026-07-05T08:00:00Z",
    relevance: "high",
    tags: ["phishing", "docusign", "credential-theft"],
    ttps: ["T1566.002", "T1078"],
  },
  {
    id: "threat_006",
    title: "Dark Web: Techcorp.com Data Allegedly For Sale",
    type: "data_breach",
    severity: "critical",
    source: "Dark Web Monitor",
    confidence: 72,
    description: "A threat actor claims to have obtained employee credentials from techcorp.com and is offering them for sale.",
    publishedAt: "2026-07-09T05:00:00Z",
    relevance: "high",
    tags: ["dark-web", "credentials", "data-breach", "internal"],
    ttps: ["T1589", "T1598"],
  },
];

export const MOCK_COMPLIANCE: ComplianceFramework[] = [
  {
    id: "comp_001",
    name: "ISO 27001:2022",
    version: "2022",
    description: "International standard for information security management systems",
    totalControls: 93,
    passedControls: 78,
    failedControls: 10,
    notApplicable: 5,
    score: 84,
    status: "partially_compliant",
    lastAssessed: "2026-06-15T00:00:00Z",
    nextAudit: "2026-09-15T00:00:00Z",
    category: "Information Security",
  },
  {
    id: "comp_002",
    name: "SOC 2 Type II",
    version: "2017",
    description: "Service Organization Control for security, availability, and confidentiality",
    totalControls: 64,
    passedControls: 58,
    failedControls: 6,
    notApplicable: 0,
    score: 91,
    status: "compliant",
    lastAssessed: "2026-05-01T00:00:00Z",
    nextAudit: "2027-05-01T00:00:00Z",
    category: "Trust Services",
  },
  {
    id: "comp_003",
    name: "NIST CSF 2.0",
    version: "2.0",
    description: "NIST Cybersecurity Framework for managing cybersecurity risk",
    totalControls: 108,
    passedControls: 82,
    failedControls: 20,
    notApplicable: 6,
    score: 76,
    status: "partially_compliant",
    lastAssessed: "2026-06-01T00:00:00Z",
    nextAudit: "2026-12-01T00:00:00Z",
    category: "Cybersecurity",
  },
  {
    id: "comp_004",
    name: "GDPR",
    version: "2018",
    description: "General Data Protection Regulation for EU data privacy",
    totalControls: 52,
    passedControls: 45,
    failedControls: 5,
    notApplicable: 2,
    score: 87,
    status: "partially_compliant",
    lastAssessed: "2026-07-01T00:00:00Z",
    nextAudit: "2027-01-01T00:00:00Z",
    category: "Data Privacy",
  },
  {
    id: "comp_005",
    name: "PCI DSS 4.0",
    version: "4.0",
    description: "Payment Card Industry Data Security Standard",
    totalControls: 285,
    passedControls: 220,
    failedControls: 45,
    notApplicable: 20,
    score: 77,
    status: "partially_compliant",
    lastAssessed: "2026-04-01T00:00:00Z",
    nextAudit: "2026-10-01T00:00:00Z",
    category: "Payment Security",
  },
];

export const MOCK_PENTESTS: PenTestProject[] = [
  {
    id: "pt_001",
    name: "Q3 2026 External Penetration Test",
    client: "TechCorp Industries",
    type: "web",
    status: "testing",
    startDate: "2026-07-01",
    endDate: "2026-07-31",
    tester: "Red Team - Alpha",
    scope: ["webapp-portal.techcorp.com", "api.techcorp.com", "techcorp.com"],
    findingsCount: 18,
    criticalCount: 3,
    highCount: 6,
    progress: 65,
    methodology: "OWASP Testing Guide v4.2 + PTES",
  },
  {
    id: "pt_002",
    name: "Internal Network Assessment 2026",
    client: "TechCorp Industries",
    type: "network",
    status: "reporting",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    tester: "Blue Team - Charlie",
    scope: ["10.0.0.0/8 Internal Network", "DMZ Segment", "Core Switches"],
    findingsCount: 24,
    criticalCount: 2,
    highCount: 8,
    progress: 90,
    methodology: "PTES + NIST SP 800-115",
  },
  {
    id: "pt_003",
    name: "AWS Cloud Security Assessment",
    client: "TechCorp Industries",
    type: "cloud",
    status: "planning",
    startDate: "2026-08-01",
    endDate: "2026-08-31",
    tester: "Red Team - Beta",
    scope: ["AWS us-east-1 Production", "S3 Buckets", "IAM Configuration", "EC2 Instances"],
    findingsCount: 0,
    criticalCount: 0,
    highCount: 0,
    progress: 10,
    methodology: "AWS Security Maturity Model + CIS AWS Benchmarks",
  },
];

export const MOCK_TRAINING: TrainingCourse[] = [
  {
    id: "tr_001",
    title: "Advanced Threat Detection & Response",
    description: "Master enterprise threat detection techniques using SIEM, EDR, and threat hunting methodologies.",
    category: "Threat Intelligence",
    difficulty: "advanced",
    duration: 480,
    modules: 12,
    enrolled: 1284,
    rating: 4.8,
    progress: 75,
    completed: false,
    certificationAvailable: true,
    tags: ["SIEM", "EDR", "threat-hunting", "SOC"],
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=220&fit=crop",
  },
  {
    id: "tr_002",
    title: "Penetration Testing Fundamentals",
    description: "Comprehensive introduction to ethical hacking and penetration testing methodologies.",
    category: "Penetration Testing",
    difficulty: "intermediate",
    duration: 360,
    modules: 9,
    enrolled: 3421,
    rating: 4.9,
    progress: 100,
    completed: true,
    certificationAvailable: true,
    tags: ["ethical-hacking", "OWASP", "Metasploit", "Kali"],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=220&fit=crop",
  },
  {
    id: "tr_003",
    title: "Phishing Awareness & Social Engineering Defense",
    description: "Recognize and defend against social engineering attacks and phishing campaigns.",
    category: "Cyber Awareness",
    difficulty: "beginner",
    duration: 90,
    modules: 5,
    enrolled: 8920,
    rating: 4.7,
    progress: 40,
    completed: false,
    certificationAvailable: false,
    tags: ["phishing", "social-engineering", "awareness"],
    thumbnail: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=220&fit=crop",
  },
  {
    id: "tr_004",
    title: "Cloud Security Architecture & Best Practices",
    description: "Secure AWS, Azure, and GCP environments with industry-leading security controls.",
    category: "Cloud Security",
    difficulty: "advanced",
    duration: 420,
    modules: 14,
    enrolled: 2156,
    rating: 4.6,
    progress: 20,
    completed: false,
    certificationAvailable: true,
    tags: ["AWS", "Azure", "GCP", "cloud-security"],
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=220&fit=crop",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif_001",
    type: "critical",
    title: "Critical Vulnerability Detected",
    message: "SQL Injection found in webapp-portal.techcorp.com — Immediate action required",
    read: false,
    createdAt: "2026-07-09T08:23:00Z",
    link: "/dashboard/vulnerabilities",
    module: "Vulnerability",
  },
  {
    id: "notif_002",
    type: "alert",
    title: "Active Incident: Ransomware Detected",
    message: "Ransomware activity detected on WS-042. Incident INC-001 created.",
    read: false,
    createdAt: "2026-07-09T07:30:00Z",
    link: "/dashboard/incidents",
    module: "Incident Response",
  },
  {
    id: "notif_003",
    type: "warning",
    title: "Dark Web Mention Detected",
    message: "Possible techcorp.com credential leak found on dark web forum.",
    read: false,
    createdAt: "2026-07-09T05:00:00Z",
    link: "/dashboard/threats",
    module: "Threat Intel",
  },
  {
    id: "notif_004",
    type: "info",
    title: "Compliance Audit Scheduled",
    message: "ISO 27001 quarterly audit scheduled for September 15, 2026.",
    read: true,
    createdAt: "2026-07-08T14:00:00Z",
    link: "/dashboard/compliance",
    module: "Compliance",
  },
  {
    id: "notif_005",
    type: "success",
    title: "Vulnerability Resolved",
    message: "Missing Security Headers (vuln_006) has been successfully remediated.",
    read: true,
    createdAt: "2026-07-08T10:00:00Z",
    link: "/dashboard/vulnerabilities",
    module: "Vulnerability",
  },
];

export const RISK_TREND_DATA: ChartDataPoint[] = [
  { name: "Jan", value: 82, value2: 65 },
  { name: "Feb", value: 78, value2: 68 },
  { name: "Mar", value: 80, value2: 70 },
  { name: "Apr", value: 75, value2: 73 },
  { name: "May", value: 72, value2: 75 },
  { name: "Jun", value: 71, value2: 78 },
  { name: "Jul", value: 68, value2: 82 },
];

export const VULN_BY_SEVERITY: ChartDataPoint[] = [
  { name: "Critical", value: 12, color: "#EF4444" },
  { name: "High", value: 35, color: "#F97316" },
  { name: "Medium", value: 58, color: "#F59E0B" },
  { name: "Low", value: 32, color: "#22C55E" },
  { name: "Info", value: 10, color: "#06B6D4" },
];

export const THREAT_ACTIVITY_DATA: ChartDataPoint[] = [
  { name: "Mon", value: 45, value2: 12 },
  { name: "Tue", value: 62, value2: 18 },
  { name: "Wed", value: 38, value2: 8 },
  { name: "Thu", value: 71, value2: 23 },
  { name: "Fri", value: 55, value2: 15 },
  { name: "Sat", value: 28, value2: 6 },
  { name: "Sun", value: 19, value2: 4 },
];

export const COMPLIANCE_DATA: ChartDataPoint[] = [
  { name: "ISO 27001", value: 84, color: "#2563EB" },
  { name: "SOC 2", value: 91, color: "#22C55E" },
  { name: "NIST CSF", value: 76, color: "#F59E0B" },
  { name: "GDPR", value: 87, color: "#8B5CF6" },
  { name: "PCI DSS", value: 77, color: "#06B6D4" },
];

export const ASSET_BY_TYPE: ChartDataPoint[] = [
  { name: "Servers", value: 48, color: "#2563EB" },
  { name: "Web Apps", value: 36, color: "#22C55E" },
  { name: "Cloud", value: 89, color: "#8B5CF6" },
  { name: "Network", value: 67, color: "#F59E0B" },
  { name: "Endpoints", value: 72, color: "#06B6D4" },
];

export const PRICING_PLANS = [
  {
    id: "free",
    name: "Starter",
    price: 0,
    period: "forever",
    description: "Perfect for individuals starting their security journey",
    features: [
      "5 Asset Scans/month",
      "Basic Vulnerability Assessment",
      "Threat Intel Feed (Limited)",
      "1 User",
      "Community Support",
      "Security Score Dashboard",
      "Basic Compliance Checks",
      "Email Alerts",
    ],
    notIncluded: ["Penetration Testing", "Incident Response", "Advanced Analytics", "API Access", "Priority Support"],
    color: "dark-border",
    popular: false,
    cta: "Get Started Free",
  },
  {
    id: "professional",
    name: "Professional",
    price: 149,
    period: "month",
    description: "Ideal for security professionals and growing businesses",
    features: [
      "Unlimited Asset Scans",
      "Advanced Vulnerability Management",
      "Full Threat Intelligence",
      "Up to 25 Users",
      "Penetration Testing Projects",
      "Incident Response Module",
      "Compliance Management (5 Frameworks)",
      "AI Security Assistant",
      "Advanced Analytics & Reports",
      "Priority Email Support",
      "API Access",
      "PDF Report Generation",
    ],
    notIncluded: ["Custom SIEM Integration", "Dedicated CSM", "On-premise Deployment"],
    color: "cyber-blue",
    popular: true,
    cta: "Start Free Trial",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 499,
    period: "month",
    description: "Full-spectrum security for enterprises and large organizations",
    features: [
      "Everything in Professional",
      "Unlimited Users",
      "Custom SIEM Integration",
      "Red Team Operations",
      "All Compliance Frameworks",
      "Dark Web Monitoring",
      "AI-Powered SOC Automation",
      "Executive Security Dashboard",
      "Dedicated Customer Success Manager",
      "Custom Integrations & API",
      "On-premise Deployment Option",
      "24/7 Priority Support",
      "SLA Guarantee",
    ],
    notIncluded: [],
    color: "cyber-green",
    popular: false,
    cta: "Contact Sales",
  },
];

export const TEAM_MEMBERS = [
  {
    id: "mem_001",
    name: "Alex Morgan",
    email: "alex.morgan@techcorp.com",
    role: "security_analyst",
    department: "Security Operations",
    status: "active",
    lastActive: "2026-07-09T09:15:00Z",
    mfaEnabled: true,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=64&h=64&fit=crop&crop=face",
  },
  {
    id: "mem_002",
    name: "Sarah Chen",
    email: "sarah.chen@techcorp.com",
    role: "pen_tester",
    department: "Red Team",
    status: "active",
    lastActive: "2026-07-09T08:00:00Z",
    mfaEnabled: true,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=64&h=64&fit=crop&crop=face",
  },
  {
    id: "mem_003",
    name: "Mike Johnson",
    email: "mike.johnson@techcorp.com",
    role: "compliance_officer",
    department: "GRC",
    status: "active",
    lastActive: "2026-07-08T17:00:00Z",
    mfaEnabled: false,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=64&h=64&fit=crop&crop=face",
  },
  {
    id: "mem_004",
    name: "Elena Vasquez",
    email: "elena.vasquez@techcorp.com",
    role: "enterprise_admin",
    department: "IT Security",
    status: "active",
    lastActive: "2026-07-09T07:30:00Z",
    mfaEnabled: true,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=64&h=64&fit=crop&crop=face",
  },
];

export const SOLUTIONS = [
  {
    id: "sol_001",
    title: "Vulnerability Assessment",
    description: "Continuously scan your entire attack surface for vulnerabilities before attackers find them.",
    icon: "Shield",
    color: "cyber-blue",
    features: ["Web Application Scanning", "Network Vulnerability Assessment", "Cloud Security Posture", "CVSS Scoring & Prioritization", "Automated Remediation Guidance"],
    useCases: ["E-commerce security", "API security testing", "Cloud infrastructure review"],
  },
  {
    id: "sol_002",
    title: "Penetration Testing",
    description: "Simulate real-world cyberattacks to identify exploitable weaknesses in your defenses.",
    icon: "Target",
    color: "cyber-red",
    features: ["Web App Pen Testing", "Network Penetration Testing", "Mobile App Testing", "Social Engineering", "Red Team Operations", "Detailed Reporting"],
    useCases: ["Compliance requirements", "Pre-launch security testing", "Annual security audits"],
  },
  {
    id: "sol_003",
    title: "Threat Intelligence",
    description: "Stay ahead of threats with real-time intelligence from global security feeds and dark web monitoring.",
    icon: "Activity",
    color: "cyber-purple",
    features: ["Real-time Threat Feeds", "IOC Management", "Dark Web Monitoring", "APT Tracking", "Threat Hunting", "Intelligence Reports"],
    useCases: ["Financial sector defense", "Critical infrastructure protection", "Nation-state threat monitoring"],
  },
  {
    id: "sol_004",
    title: "Compliance Management",
    description: "Achieve and maintain compliance with ISO 27001, SOC 2, NIST, GDPR, PCI DSS, and more.",
    icon: "CheckCircle",
    color: "cyber-green",
    features: ["Framework Management", "Control Assessment", "Evidence Collection", "Audit Management", "Risk Register", "Automated Reporting"],
    useCases: ["GDPR compliance", "SOC 2 certification", "ISO 27001 audits"],
  },
  {
    id: "sol_005",
    title: "Incident Response",
    description: "Detect, contain, and recover from security incidents faster with AI-assisted response playbooks.",
    icon: "AlertTriangle",
    color: "cyber-yellow",
    features: ["Incident Detection & Triage", "Playbook Automation", "Timeline Analysis", "Evidence Management", "Root Cause Analysis", "Lessons Learned"],
    useCases: ["SOC operations", "Breach response", "Regulatory notification"],
  },
  {
    id: "sol_006",
    title: "AI Security Assistant",
    description: "Your 24/7 AI-powered security advisor for threat analysis, log investigation, and recommendations.",
    icon: "Cpu",
    color: "cyber-cyan",
    features: ["Natural Language Log Analysis", "Threat Explanation", "Risk Prioritization", "Best Practice Recommendations", "Automated Report Generation", "Knowledge Base"],
    useCases: ["Junior analyst support", "Rapid triage", "Executive briefing generation"],
  },
];

export const AI_MESSAGES = [
  {
    role: "assistant",
    content: "Hello! I'm GC-AI, your intelligent cybersecurity assistant. I can help you analyze threats, investigate incidents, review logs, prioritize vulnerabilities, and generate security reports. What would you like to explore today?",
    timestamp: "2026-07-09T09:00:00Z",
  },
  {
    role: "user",
    content: "What are my most critical vulnerabilities right now?",
    timestamp: "2026-07-09T09:01:00Z",
  },
  {
    role: "assistant",
    content: `Based on your current security posture, here are your **top 3 critical vulnerabilities** requiring immediate attention:\n\n1. **SQL Injection (CVSS 9.8)** — webapp-portal.techcorp.com\n   - Risk: Complete database compromise\n   - Action: Deploy parameterized queries immediately\n\n2. **Default Credentials on Switch** (CVSS 9.3) — switch-core-01\n   - Risk: Full network access\n   - Action: Change credentials + implement ACL\n\n3. **RCE via Deserialization** (CVSS 9.6) — api.techcorp.com\n   - Risk: Remote code execution\n   - Action: Patch serialization library urgently\n\nWould you like me to generate a remediation plan or create an executive report for these findings?`,
    timestamp: "2026-07-09T09:01:05Z",
  },
];
